OLLAMA_MODEL = "qwen3:8b"
VISION_MODEL = "llava"
FAISS_INDEX_PATH = "data/faiss_index"
PDF_UPLOAD_DIR = "data/pdfs"
IMAGE_UPLOAD_DIR = "data/uploads"
IMAGE_OUTPUT_DIR = "data/images"
OLLAMA_BASE_URL = "http://127.0.0.1:11434"
